/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora04;

import java.awt.image.ImageObserver;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Aura Uribe
 */
public class Calculadora04 extends javax.swing.JFrame {
//Declaracion de Varibles
    //n1-->Numero 1
    //n2-->Numero 2
    //s-->Signo empleado
    String n1,n2,s;
    /**
     * Creates new form Calculadora03
     */
    public Calculadora04() {
        initComponents();
        setLocationRelativeTo(null);
        //setResizable(false);
  setIconImage(new ImageIcon(getClass().getResource("/Imagenes/konoha.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false); ImageIcon uno=new 
ImageIcon(this.getClass().getResource("/Imagenes/fondo.jpg")); 
JLabel fondo= new JLabel(); fondo.setIcon(uno); 
getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Conversiones = new javax.swing.ButtonGroup();
        Display = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        opthex = new javax.swing.JRadioButton();
        optdec = new javax.swing.JRadioButton();
        optoct = new javax.swing.JRadioButton();
        optbin = new javax.swing.JRadioButton();
        conver = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnbin = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        btnoct = new javax.swing.JButton();
        btndec = new javax.swing.JButton();
        btnhex = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(478, 550));
        getContentPane().setLayout(null);

        Display.setFont(new java.awt.Font("Syncopate", 0, 22)); // NOI18N
        Display.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Display);
        Display.setBounds(20, 60, 440, 50);

        jLabel1.setFont(new java.awt.Font("Neostar", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Calculadora-Convertidor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 434, 50);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        Conversiones.add(opthex);
        opthex.setFont(new java.awt.Font("Syncopate", 0, 10)); // NOI18N
        opthex.setForeground(new java.awt.Color(255, 0, 0));
        opthex.setText("Hexadecimal");
        opthex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opthexActionPerformed(evt);
            }
        });
        jPanel2.add(opthex);
        opthex.setBounds(310, 10, 120, 21);

        Conversiones.add(optdec);
        optdec.setFont(new java.awt.Font("Syncopate", 0, 10)); // NOI18N
        optdec.setForeground(new java.awt.Color(255, 0, 0));
        optdec.setText("Decimal");
        optdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optdecActionPerformed(evt);
            }
        });
        jPanel2.add(optdec);
        optdec.setBounds(200, 10, 83, 21);

        Conversiones.add(optoct);
        optoct.setFont(new java.awt.Font("Syncopate", 0, 10)); // NOI18N
        optoct.setForeground(new java.awt.Color(255, 0, 0));
        optoct.setText("Octal");
        optoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optoctActionPerformed(evt);
            }
        });
        jPanel2.add(optoct);
        optoct.setBounds(110, 10, 67, 21);

        Conversiones.add(optbin);
        optbin.setFont(new java.awt.Font("Syncopate", 0, 10)); // NOI18N
        optbin.setForeground(new java.awt.Color(255, 0, 0));
        optbin.setText("Binario");
        optbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optbinActionPerformed(evt);
            }
        });
        jPanel2.add(optbin);
        optbin.setBounds(10, 10, 93, 21);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 120, 440, 40);

        conver.setFont(new java.awt.Font("Syncopate", 0, 18)); // NOI18N
        conver.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(conver);
        conver.setBounds(10, 400, 290, 50);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        jButton1.setText("A");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 170, 60, 40);

        btn2.setBackground(new java.awt.Color(255, 0, 0));
        btn2.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(180, 230, 60, 40);

        btn1.setBackground(new java.awt.Color(255, 0, 0));
        btn1.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(110, 230, 60, 40);

        btnbin.setBackground(new java.awt.Color(255, 0, 0));
        btnbin.setFont(new java.awt.Font("Syncopate", 0, 11)); // NOI18N
        btnbin.setText("Bin");
        btnbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinActionPerformed(evt);
            }
        });
        getContentPane().add(btnbin);
        btnbin.setBounds(310, 400, 70, 20);

        btnB.setBackground(new java.awt.Color(255, 0, 0));
        btnB.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB);
        btnB.setBounds(110, 170, 60, 40);

        btnC.setBackground(new java.awt.Color(255, 0, 0));
        btnC.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(180, 170, 60, 40);

        btnD.setBackground(new java.awt.Color(255, 0, 0));
        btnD.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        getContentPane().add(btnD);
        btnD.setBounds(250, 170, 60, 40);

        btn4.setBackground(new java.awt.Color(255, 0, 0));
        btn4.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(320, 230, 60, 40);

        btn7.setBackground(new java.awt.Color(255, 0, 0));
        btn7.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(110, 290, 60, 40);

        btn3.setBackground(new java.awt.Color(255, 0, 0));
        btn3.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(250, 230, 60, 40);

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Galaxy", 0, 9)); // NOI18N
        jButton11.setText("C");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(390, 290, 60, 40);

        btn6.setBackground(new java.awt.Color(255, 0, 0));
        btn6.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(40, 290, 60, 40);

        jButton13.setBackground(new java.awt.Color(255, 0, 0));
        jButton13.setFont(new java.awt.Font("Neostar", 0, 24)); // NOI18N
        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(110, 350, 60, 40);

        jButton14.setBackground(new java.awt.Color(255, 0, 0));
        jButton14.setFont(new java.awt.Font("Galaxy", 0, 9)); // NOI18N
        jButton14.setText("CE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(320, 290, 60, 40);

        btn9.setBackground(new java.awt.Color(255, 0, 0));
        btn9.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(250, 290, 60, 40);

        jButton16.setBackground(new java.awt.Color(255, 0, 0));
        jButton16.setFont(new java.awt.Font("Neostar", 0, 24)); // NOI18N
        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(40, 350, 60, 40);

        jButton17.setBackground(new java.awt.Color(255, 0, 0));
        jButton17.setFont(new java.awt.Font("Neostar", 0, 24)); // NOI18N
        jButton17.setText("/");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(250, 350, 60, 40);

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setFont(new java.awt.Font("Neostar", 0, 24)); // NOI18N
        jButton18.setText("=");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(320, 350, 130, 40);

        btn5.setBackground(new java.awt.Color(255, 0, 0));
        btn5.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(390, 230, 60, 40);

        btnE.setBackground(new java.awt.Color(255, 0, 0));
        btnE.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        getContentPane().add(btnE);
        btnE.setBounds(320, 170, 60, 40);

        jButton21.setBackground(new java.awt.Color(255, 0, 0));
        jButton21.setFont(new java.awt.Font("Neostar", 0, 24)); // NOI18N
        jButton21.setText("*");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(180, 350, 60, 40);

        btnoct.setBackground(new java.awt.Color(255, 0, 0));
        btnoct.setFont(new java.awt.Font("Syncopate", 0, 11)); // NOI18N
        btnoct.setText("oct");
        btnoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoctActionPerformed(evt);
            }
        });
        getContentPane().add(btnoct);
        btnoct.setBounds(390, 400, 70, 20);

        btndec.setBackground(new java.awt.Color(255, 0, 0));
        btndec.setFont(new java.awt.Font("Syncopate", 0, 11)); // NOI18N
        btndec.setText("dec");
        btndec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecActionPerformed(evt);
            }
        });
        getContentPane().add(btndec);
        btndec.setBounds(310, 430, 70, 20);

        btnhex.setBackground(new java.awt.Color(255, 0, 0));
        btnhex.setFont(new java.awt.Font("Syncopate", 0, 11)); // NOI18N
        btnhex.setText("hex");
        btnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhexActionPerformed(evt);
            }
        });
        getContentPane().add(btnhex);
        btnhex.setBounds(390, 430, 70, 20);

        btn8.setBackground(new java.awt.Color(255, 0, 0));
        btn8.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(180, 290, 60, 40);

        btnF.setBackground(new java.awt.Color(255, 0, 0));
        btnF.setFont(new java.awt.Font("Galaxy", 0, 12)); // NOI18N
        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        getContentPane().add(btnF);
        btnF.setBounds(390, 170, 60, 40);

        btn0.setBackground(new java.awt.Color(255, 0, 0));
        btn0.setFont(new java.awt.Font("Galactic Basic", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(40, 230, 60, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Neostar", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("José Carlos Javier Fermín");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 10, 140, 20);

        jLabel4.setFont(new java.awt.Font("Neostar", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Víctor Gallardo Manrique");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 130, 20);

        jLabel5.setFont(new java.awt.Font("Neostar", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Aura Elizabeth Uribe Gamiño");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 10, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 460, 450, 40);

        pack();
    }// </editor-fold>                        

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        // Boton 1
        Display.setText(Display.getText()+"1");
    }                                    

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        Display.setText(Display.getText()+"2");
        // TODO add your handling code here:
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"8");
    }                                    

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"9");
    }                                    
//Boton = aqui se hace todo owo
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(optbin.isSelected()){
        restaBinaria();
        sumaBinaria();
        multiplicacionBinaria();
        divisionBinaria();
        }
        if(optoct.isSelected()){
        restaOctal();
        sumaOctal();
        multiplicacionOctal();
        divisionOctal();
        }
        if(optdec.isSelected()){
        restaDecimal();
        sumaDecimal();
        multiplicacionDecimal();
        divisionDecimal();
        }
        if(opthex.isSelected()){
        restaHexadecimal();
        sumaHexadecimal();
        multiplicacionHexadecimal();
        divisionHexadecimal();
        }
        
    }                                         
public void restaHexadecimal(){
    String res,resh;
        Integer resultado,nh1,nh2;
        n2=Display.getText();
        if(s.equals("-")){
        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,16)-Integer.parseInt(n2,16);
        res=Integer.toString(resultado,16);
        resh=res.toUpperCase();
        Display.setText(resh);
            }
        }
    }
    public void sumaHexadecimal(){
    String res,resh;
        Integer resultado,nh1,nh2;
        n2=Display.getText();
        if(s.equals("+")){
        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,16)+Integer.parseInt(n2,16);
        res=Integer.toString(resultado,16);
        resh=res.toUpperCase();
        Display.setText(resh);
            }
        }
    }
    public void multiplicacionHexadecimal(){
    String res,resh;
        Integer resultado,nh1,nh2;
        n2=Display.getText();
        if(s.equals("*")){
        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,16)*Integer.parseInt(n2,16);
        res=Integer.toString(resultado,16);
        resh=res.toUpperCase();
        Display.setText(resh);
            }
        }
    }
    public void divisionHexadecimal(){
    String res,resh;
        Integer resultado,nh1,nh2;
        n2=Display.getText();
        if(s.equals("/")){
        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,16)/Integer.parseInt(n2,16);
        res=Integer.toString(resultado,16);
        resh=res.toUpperCase();
        Display.setText(resh);
            }
        }
    }
    public void restaOctal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("-")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,8)-Integer.parseInt(n2,8);
        res=Integer.toString(resultado,8);
        Display.setText(res);
            }
        }
    }
    public void sumaOctal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("+")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,8)+Integer.parseInt(n2,8);
        res=Integer.toString(resultado,8);
        Display.setText(res);
            }
        }
    }
    public void divisionOctal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("/")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,8)/Integer.parseInt(n2,8);
        res=Integer.toString(resultado,8);
        Display.setText(res);
            }
        }
    }
    public void divisionBinaria(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("/")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,2)/Integer.parseInt(n2,2);
        res=Integer.toString(resultado,2);
        Display.setText(res);
            }
        }
    }
    public void multiplicacionOctal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("*")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,8)*Integer.parseInt(n2,8);
        res=Integer.toString(resultado,8);
        Display.setText(res);
            }
        }
    }
    public void restaBinaria(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("-")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,2)-Integer.parseInt(n2,2);
        res=Integer.toString(resultado,2);
        Display.setText(res);
            }
        }
    }
    public void sumaDecimal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("+")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1)+Integer.parseInt(n2);
        res=Integer.toString(resultado);
        Display.setText(res);
            }
        }
    }
    public void sumaBinaria(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("+")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,2)+Integer.parseInt(n2,2);
        res=Integer.toString(resultado,2);
        Display.setText(res);
            }
        }
    }
    public void restaDecimal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("-")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1)-Integer.parseInt(n2);
        res=Integer.toString(resultado);
        Display.setText(res);
            }
        }
    }
    public void multiplicacionDecimal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("*")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1)*Integer.parseInt(n2);
        res=Integer.toString(resultado);
        Display.setText(res);
            }
        }
    }
    public void divisionDecimal(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("/")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1)/Integer.parseInt(n2);
        res=Integer.toString(resultado);
        Display.setText(res);
            }
        }
    }
    public void multiplicacionBinaria(){
    String res;
        Integer resultado;
        n2=Display.getText();
                    if(s.equals("*")){

        if (!n2.equals("")){
        resultado=Integer.parseInt(n1,2)*Integer.parseInt(n2,2);
        res=Integer.toString(resultado,2);
        Display.setText(res);
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // Boton A
        /*if(optbin.isSelected()){
        jButton1.setEnabled(false);
        }
        if(opthex.isSelected()){
        jButton1.setEnabled(true);
        }*/
        Display.setText(Display.getText()+"A");
        
    }                                        

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // Boton B
        Display.setText(Display.getText()+"B");
    }                                    

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {                                     
       // Boton C
        Display.setText(Display.getText()+"C");
    }                                    

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // Boton D
        Display.setText(Display.getText()+"D");
    }                                    

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // Boton E
        Display.setText(Display.getText()+"E");
    }                                    

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {                                     
       // Boton F
        Display.setText(Display.getText()+"F");
    }                                    

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        // Boton 0
        Display.setText(Display.getText()+"0");
    }                                    

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"3");
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"4");
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"5");
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"6");
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Display.setText(Display.getText()+"7");
    }                                    

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //Boton para borrar caracteres presentes en Display (uno por uno)
        String c;
        c=Display.getText();
        if (c.length()>0){
        c=c.substring(0,c.length()-1);
        Display.setText(c);
        }
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Display.setText("");
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        // Boton +
        if (!Display.getText().equals("")){
        n1=Display.getText();
        s="+";
        Display.setText("");
        }
    }                                         
//Comparar Letras Hexadecimal
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        // Boton -
        if (!Display.getText().equals("")){
        n1=Display.getText();
        comHex(n1);
        s="-";
        Display.setText("");
        }
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (!Display.getText().equals("")){
        n1=Display.getText();
        s="*";
        Display.setText("");
        }
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if (!Display.getText().equals("")){
        n1=Display.getText();
        s="/";
        Display.setText("");
        }        // TODO add your handling code here:
    }                                         

    private void optbinActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (optbin.isSelected()){
        
        jButton1.setEnabled(false);
        btnB.setEnabled(false);
        btnC.setEnabled(false);
        btnD.setEnabled(false);
        btnE.setEnabled(false);
        btnF.setEnabled(false);
        btn9.setEnabled(false);
        btn8.setEnabled(false);
        btn7.setEnabled(false);
        btn6.setEnabled(false);
        btn5.setEnabled(false);
        btn4.setEnabled(false);
        btn3.setEnabled(false);
        btn2.setEnabled(false);
        }
        // TODO add your handling code here:
    }                                      

    private void optoctActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if (optoct.isSelected()){
        jButton1.setEnabled(false);
        btnB.setEnabled(false);
        btnC.setEnabled(false);
        btnD.setEnabled(false);
        btnE.setEnabled(false);
        btnF.setEnabled(false);
        btn9.setEnabled(false);
        btn8.setEnabled(false);
        btn7.setEnabled(true);
        btn6.setEnabled(true);
        btn5.setEnabled(true);
        btn4.setEnabled(true);
        btn3.setEnabled(true);
        btn2.setEnabled(true);
        }
    }                                      

    private void opthexActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if (opthex.isSelected()){
        
        jButton1.setEnabled(true);
        btnB.setEnabled(true);
        btnC.setEnabled(true);
        btnD.setEnabled(true);
        btnE.setEnabled(true);
        btnF.setEnabled(true);
        btn9.setEnabled(true);
        btn8.setEnabled(true);
        btn7.setEnabled(true);
        btn6.setEnabled(true);
        btn5.setEnabled(true);
        btn4.setEnabled(true);
        btn3.setEnabled(true);
        btn2.setEnabled(true);
        }
    }                                      

    private void btnbinActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String n8,resh;
        Integer num8;
        if(optoct.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,8);
        n8=Integer.toBinaryString(num8);
        conver.setText(n8);
        }
        if(optdec.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8);
        n8=Integer.toBinaryString(num8);
        conver.setText(n8);
        }
        if(opthex.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,16);
        n8=Integer.toBinaryString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if (optbin.isSelected()){
        n8=Display.getText();
        conver.setText(n8);
        }
    }                                      

    private void optdecActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if (optdec.isSelected()){
            
            jButton1.setEnabled(false);
        btnB.setEnabled(false);
        btnC.setEnabled(false);
        btnD.setEnabled(false);
        btnE.setEnabled(false);
        btnF.setEnabled(false);
        btn9.setEnabled(true);
        btn8.setEnabled(true);
        btn7.setEnabled(true);
        btn6.setEnabled(true);
        btn5.setEnabled(true);
        btn4.setEnabled(true);
        btn3.setEnabled(true);
        btn2.setEnabled(true);
    }
    }                                      

    private void btnoctActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String n8,resh;
        Integer num8;
        if(optbin.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,2);
        n8=Integer.toOctalString(num8);
        conver.setText(n8);
        }
        if(optdec.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8);
        n8=Integer.toOctalString(num8);
        conver.setText(n8);
        }
        if(opthex.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,16);
        n8=Integer.toOctalString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if (optoct.isSelected()){
        n8=Display.getText();
        conver.setText(n8);
        }
    }                                      

    private void btndecActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String n8,resh;
        Integer num8;
        if(optoct.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,8);
        n8=Integer.toString(num8);
        conver.setText(n8);
        }
        if(optbin.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,2);
        n8=Integer.toString(num8);
        conver.setText(n8);
        }
        if(opthex.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,16);
        n8=Integer.toString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if (optdec.isSelected()){
        n8=Display.getText();
        conver.setText(n8);
        }
    }                                      

    private void btnhexActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String n8,resh;
        Integer num8;
        if(optoct.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,8);
        n8=Integer.toHexString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if(optdec.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8);
        n8=Integer.toHexString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if(optbin.isSelected()){
        n8=Display.getText();
        num8=Integer.parseInt(n8,2);
        n8=Integer.toHexString(num8);
        resh=n8.toUpperCase();
        conver.setText(resh);
        }
        if (opthex.isSelected()){
        n8=Display.getText();
        conver.setText(n8);
        }
    }                                      
public void comHex(String n1){
    if (n1.equals("A")){
    n1="10";
    }
    if (n1.equals("B")){
    n1="11";
    }
    if (n1.equals("C")){
    n1="12";
    }
    if (n1.equals("D")){
    n1="13";
    }
    if (n1.equals("E")){
    n1="14";
    }
    if (n1.equals("F")){
    n1="15";
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora04().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup Conversiones;
    private javax.swing.JTextField Display;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnbin;
    private javax.swing.JButton btndec;
    private javax.swing.JButton btnhex;
    private javax.swing.JButton btnoct;
    private javax.swing.JTextField conver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton optbin;
    private javax.swing.JRadioButton optdec;
    private javax.swing.JRadioButton opthex;
    private javax.swing.JRadioButton optoct;
    // End of variables declaration                   
}
